print(typeof(io.stdin))
local input = io.stdin:scan()
print(`input is {input}`)

-- local stack = require('@pls/stack')
-- print("yoo")
-- local path = fs.path("hello.luau")
-- path.ext = "lul"
-- path.stem = "eeaeawdawdaw"
-- print(path.type)
-- print(typeof(path))
-- print(path.ext, path.name, path.stem)
-- path.dir = fs.path('../')
-- local fw = io.filewriter("aec")
-- fw:close()
-- fs.copy("aec", "aec2", 'overwrite existing')
-- os.execute("echo hello")
